::ScriptNameScriptNameScriptName
::@Authors FB
::@Version 0.1.0
::@Description
::  Description Description Description
::@Syntax
::  xxx.cmd [arg1] [/option1 data]
::@Variables
::  @, @STR, @EXIT_CODE
::@Arguments
::  %1: arg1arg1
::  %2: arg2arg2
::    arg2arg2arg2arg2arg2arg2
::  -OPT1: opt1opt1opt1
::    opt1opt1opt1opt1opt1opt1
::  -OPT2: opt2opt2opt2
::@Outputs
::  %@%: outputoutputoutput
::  %@LIST%: listlistlistlist
::  FILE: filefilefilefilefile
::    filefilefilefilefilefilefilefilefilefile
::  STDOUT: stdoutstdoutstdoutstdout
::    stdoutstdoutstdoutstdoutstdoutstdoutstdout
::  STDERR: stderrstderrstderrstderr
::@Returns
::  0: returnreturnreturnreturn
::  1: returnreturnreturnreturn
::    returnreturnreturnreturn
::  N: returnreturnreturnreturn
::@Examples
::  C:\>examplesexamplesexamples
::  C:\>examplesexamplesexamplesexamples
::  examplesexamplesexamplesexamplesexamplesexamples
::@Notes
::  notesnotesnotesnotesnotesnotesnotesnotes
::  notesnotesnotes:
::    notesnotesnotesnotesnotesnotes
::    notesnotesnotesnotesnotesnotesnotesnotes
::  notesnotesnotesnotesnotesnotes
::  notesnotesnotesnotesnotesnotesnotesnotesnotesnotes

::Bin:XXXXX.EXE::
::Script:XXX.XXXX.CMD::
::File:XXXX.XXX::
::Folder:XXXXX::

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

codecodecodecodecode
codecodecodecodecodecodecodecode
codecodecode
codecodecodecodecodecodecodecodecodecode
codecodecodecodecode
codecodecode
EXIT /B
